name: Generate 3D Contribution Profile

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate animated 3D contribution SVGs
    runs-on: ubuntu-latest
    steps:
      - name: Generate profile 3D contribution
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
